package:
  name: sortedcontainers
  version: "1.5.3"

source:
  fn: sortedcontainers-1.5.3.tar.gz
  url: https://files.pythonhosted.org/packages/88/9e/949ef5f596f8b1e5776d148c1a4f16129b671ed377f6fa38e7e3f170cb84/sortedcontainers-1.5.3.tar.gz
  md5: 9536cd5a99ab8e65b47059420e29f6ff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sortedcontainers = sortedcontainers:main
    #
    # Would create an entry point called sortedcontainers that calls sortedcontainers.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - sortedcontainers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - tox
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache Software License
  summary: 'Python Sorted Container Types: SortedList, SortedDict, and SortedSet'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
