package:
  name: pysam
  version: "0.8.4"

source:
  fn: pysam-0.8.4.tar.gz
  url: https://files.pythonhosted.org/packages/27/89/bf8c44d0bfe9d0cadab062893806994c168c9f490f67370fc56d6e8ba224/pysam-0.8.4.tar.gz
  md5: 1357038e50e49b79ba02868ac2dbe2c1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysam = pysam:main
    #
    # Would create an entry point called pysam that calls pysam.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pysam
    - pysam.include
    # - pysam.include.htslib
    # - pysam.include.htslib.htslib
    # - pysam.include.samtools
    # - pysam.include.samtools.win32

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pysam-developers/pysam
  license: MIT
  summary: 'pysam'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
