package:
  name: pytest-datafiles
  version: "0.2"

source:
  fn: pytest-datafiles-0.2.tar.gz
  url: https://files.pythonhosted.org/packages/7e/19/a6519fb041d5ba2f41de21adc9101d1f01f4d531e5dbf385f305539dd1eb/pytest-datafiles-0.2.tar.gz
  md5: c4ef8cfed3f5ef48b1982854888fcaab
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytest-datafiles = pytest-datafiles:main
    #
    # Would create an entry point called pytest-datafiles that calls pytest-datafiles.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - py
    - pytest

  run:
    - python
    - setuptools
    - py
    - pytest

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/omarkohl/pytest-datafiles
  license: MIT License
  summary: "py.test plugin to create a 'tmpdir' containing predefined files/directories."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
